'use client'

import { useEffect, useRef } from 'react'
import Image from 'next/image'
import { Copy } from 'lucide-react'
import { toast } from 'sonner'
import { track, EVENTS } from '@/lib/analytics'

// ─── Sample kit data ───────────────────────────────────────────────────────────
// Real Allbirds Men's Tree Runners (Shopify) — generated by the tool in testing.

const SAMPLE_COPY = {
  description: `Meet the runner that runs on trees. Born from a simple idea—that footwear should feel as good as it looks, and do right by the planet while it's at it—the Men's Tree Runners reimagine the everyday sneaker from the ground up. Crafted from sustainably harvested eucalyptus tree fiber, the silky-smooth upper breathes effortlessly, keeping feet cool on warm commutes and long weekend wanders. A natural rubber sole delivers the kind of lightweight, cloud-soft cushioning that makes miles disappear. Minimalist lines and a clean silhouette mean these lightweight breathable sneakers pair just as easily with joggers as they do with chinos. No-show socks optional. Machine washable when life gets messy. Designed for doers, thinkers, and anyone who believes comfort and conscience belong in the same shoe. Slip into a pair and discover why sustainable eucalyptus fiber running shoes have quietly become the go-to for everyday adventures.`,
  bullets: [
    'Crafted from sustainably harvested eucalyptus tree fiber for all-day breathability',
    'Featherlight feel keeps feet cool on warm-weather commutes and weekend walks',
    'Natural rubber sole delivers cloud-soft cushioning with every step',
    'Minimalist silhouette pairs effortlessly with joggers, shorts, or chinos',
    'Machine washable design makes messy days surprisingly low-maintenance',
  ] as const,
  tweet: `Three months in my Tree Runners and they somehow feel better than day one. Lightest shoes I've ever owned, and knowing they're made from trees? Just makes the walk to coffee hit different. #everydaycomfort`,
}

// ─── Image configs (first 5 cards) ────────────────────────────────────────────

const MOCKUP_IMAGES = [
  {
    style:  'amazon',
    label:  'Optimized for Amazon',
    src:    '/examples/amazon.webp',
    width:  1024,
    height: 1024,
    alt:    'Allbirds Tree Runner sneaker processed by Photoroom — pure white background, Amazon style',
    aspect: 'aspect-square',
  },
  {
    style:  'instagram',
    label:  'Optimized for Instagram',
    src:    '/examples/instagram.webp',
    width:  1024,
    height: 1024,
    alt:    'Allbirds Tree Runner sneaker processed by Photoroom — AI lifestyle background, Instagram style',
    aspect: 'aspect-square',
  },
  {
    style:  'ads',
    label:  'Optimized for Ads',
    src:    '/examples/ads.webp',
    width:  1024,
    height: 1024,
    alt:    'Allbirds Tree Runner sneaker processed by Photoroom — vibrant background for ad campaigns',
    aspect: 'aspect-square',
  },
  {
    style:  'pinterest',
    label:  'Optimized for Pinterest/Email',
    src:    '/examples/pinterest.webp',
    width:  1024,
    height: 1024,
    alt:    'Allbirds Tree Runner sneaker processed by Photoroom — editorial flat lay, Pinterest style',
    aspect: 'aspect-square',
  },
  {
    style:  'tiktok',
    label:  'Optimized for TikTok Shop',
    src:    '/examples/tiktok.webp',
    width:  576,
    height: 1024,
    alt:    'Allbirds Tree Runner sneaker processed by Photoroom — 9:16 vertical format, TikTok Shop style',
    aspect: 'aspect-[9/16]',
  },
] as const

// ─── Standard mockup card ──────────────────────────────────────────────────────

function MockupCard({
  label, src, width, height, alt, aspectClass,
}: {
  label: string; src: string; width: number; height: number; alt: string; aspectClass: string
}) {
  return (
    <div className="flex flex-col gap-2">
      <span className="text-xs font-medium text-brand bg-brand-soft px-2.5 py-1 rounded-full self-start leading-none">
        {label}
      </span>
      <div className={`relative overflow-hidden rounded-xl border border-border-subtle shadow-sm bg-white ${aspectClass}`}>
        <Image
          src={src}
          alt={alt}
          width={width}
          height={height}
          className="w-full h-full object-cover"
          sizes="(max-width: 640px) 90vw, (max-width: 1024px) 45vw, 33vw"
        />
      </div>
    </div>
  )
}

// ─── Product Staging card (6th — premium / special) ───────────────────────────
// Uses amazon.webp as the base image and overlays a dark lifestyle gradient,
// urban bokeh SVG, and golden glow to simulate the Product Staging output.
// A "✨ NEW" badge + bottom text communicate this is a premium / production feature.

function StagingCard() {
  return (
    <div className="flex flex-col gap-2">
      {/* Channel label with star — visually distinct from standard labels */}
      <span className="text-xs font-medium text-brand bg-brand-soft px-2.5 py-1 rounded-full self-start leading-none flex items-center gap-1">
        <span aria-hidden="true">⭐</span>
        Product Staging · Lifestyle AI
      </span>

      {/* Card container */}
      <div
        className="relative overflow-hidden rounded-xl border border-brand/25 shadow-md aspect-square"
        role="img"
        aria-label="Allbirds sneaker in an urban lifestyle scene generated by Photoroom Product Staging AI — available on production plan"
      >
        {/* Base: real sneaker (amazon style = clean, no competing background) */}
        <Image
          src="/examples/amazon.webp"
          alt=""
          aria-hidden="true"
          width={1024}
          height={1024}
          className="w-full h-full object-cover"
          sizes="(max-width: 640px) 90vw, (max-width: 1024px) 45vw, 33vw"
        />

        {/* Dark premium overlay — simulates night/urban lifestyle scene */}
        <div
          className="absolute inset-0"
          style={{
            background: 'linear-gradient(135deg, rgba(2,8,48,0.85) 0%, rgba(38,55,122,0.72) 100%)',
          }}
          aria-hidden="true"
        />

        {/* Urban atmosphere: bokeh circles + perspective lines (SVG) */}
        <svg
          className="absolute inset-0 w-full h-full"
          viewBox="0 0 200 200"
          aria-hidden="true"
        >
          {/* Bokeh blur circles suggesting city lights */}
          <circle cx="28"  cy="32"  r="20" fill="white"   opacity="0.03" />
          <circle cx="172" cy="165" r="28" fill="white"   opacity="0.04" />
          <circle cx="158" cy="26"  r="14" fill="#6090FF" opacity="0.08" />
          <circle cx="36"  cy="170" r="16" fill="#4070FF" opacity="0.06" />
          <circle cx="170" cy="88"  r="11" fill="white"   opacity="0.04" />
          <circle cx="22"  cy="110" r="8"  fill="#8BB0FF" opacity="0.05" />
          {/* Concrete pavement lines — vanishing-point perspective */}
          <line x1="0"   y1="149" x2="200" y2="151" stroke="white" strokeWidth="0.6" opacity="0.09" />
          <line x1="0"   y1="159" x2="200" y2="161" stroke="white" strokeWidth="0.4" opacity="0.05" />
          <line x1="100" y1="149" x2="0"   y2="200" stroke="white" strokeWidth="0.5" opacity="0.07" />
          <line x1="100" y1="149" x2="200" y2="200" stroke="white" strokeWidth="0.5" opacity="0.07" />
          <line x1="100" y1="149" x2="40"  y2="200" stroke="white" strokeWidth="0.3" opacity="0.04" />
          <line x1="100" y1="149" x2="160" y2="200" stroke="white" strokeWidth="0.3" opacity="0.04" />
        </svg>

        {/* Golden glow — the "editorial lighting" cue */}
        <div
          className="absolute inset-0 flex items-center justify-center"
          aria-hidden="true"
        >
          <div className="w-32 h-32 rounded-full bg-yellow-400/20 blur-3xl" />
        </div>

        {/* ✨ NEW badge — top right */}
        <div className="absolute top-2.5 right-2.5">
          <span className="bg-brand text-white text-[10px] font-bold px-2 py-[3px] rounded-full shadow-sm">
            ✨ NEW
          </span>
        </div>

        {/* Bottom overlay text — inside card */}
        <div className="absolute bottom-0 left-0 right-0 px-3 py-2.5 bg-gradient-to-t from-black/55 to-transparent">
          <p className="text-white/70 text-[10px] leading-snug">
            AI-generated scene · Requires production plan
          </p>
        </div>
      </div>

      {/* Microtext below card — transparent about the feature */}
      <p className="text-[11px] text-fg-muted/60 leading-snug">
        Generated with Photoroom Product Staging API · Available when activating production plan
      </p>
    </div>
  )
}

// ─── Main component ────────────────────────────────────────────────────────────

export function KitShowcase() {
  const sectionRef = useRef<HTMLElement>(null)

  useEffect(() => {
    const el = sectionRef.current
    if (!el) return
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          track(EVENTS.KIT_SHOWCASE_VIEWED)
          observer.disconnect()
        }
      },
      { threshold: 0.15 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [])

  function handleCopyAll() {
    const allCopy = [
      '📝 SEO Description:\n',
      SAMPLE_COPY.description,
      '\n\n🔹 5 Bullets:\n',
      SAMPLE_COPY.bullets.map((b) => `• ${b}`).join('\n'),
      '\n\n🐦 Tweet:\n',
      SAMPLE_COPY.tweet,
    ].join('')

    navigator.clipboard
      .writeText(allCopy)
      .then(() => toast.success('Copied to clipboard ✓'))
      .catch(() => toast.error('Could not copy. Please try again.'))

    track(EVENTS.SHOWCASE_COPY_CLICKED)
  }

  function handleScrollToInput() {
    track(EVENTS.SHOWCASE_CTA_SCROLLED_TO_INPUT)
    const input = document.querySelector<HTMLInputElement>('[data-hero-input]')
    if (!input) return
    input.scrollIntoView({ behavior: 'smooth', block: 'center' })
    setTimeout(() => input.focus(), 600)
  }

  return (
    <section
      ref={sectionRef}
      className="py-24 md:py-32 bg-background-soft border-t border-border-subtle"
      aria-labelledby="showcase-heading"
    >
      <div className="max-w-5xl mx-auto px-4 sm:px-6">

        {/* ── Section header ──────────────────────────────────────────────────── */}
        <div className="text-center mb-14 flex flex-col items-center gap-4">
          <p className="text-xs font-semibold text-brand uppercase tracking-widest">
            Generated Kit Example
          </p>
          <h2
            id="showcase-heading"
            className="text-3xl sm:text-4xl font-bold tracking-tight text-fg"
          >
            See exactly what you&apos;ll get
          </h2>
          <p className="text-lg text-fg-muted max-w-[560px] text-balance">
            Paste a URL and get all of this in 30 seconds. No designer, no copywriter, no photoshoot.
          </p>
          <span className="text-xs text-fg-muted/60 border border-border-subtle rounded-full px-3 py-1">
            ★ Illustrative example — generated with the tool&apos;s real styles
          </span>
        </div>

        {/* ── Photoroom transformation showcase ──────────────────────────────── */}
        <div className="mb-10">
          <div className="rounded-2xl border border-brand/20 bg-gradient-to-br from-brand-soft/60 to-white overflow-hidden">

            {/* Header */}
            <div className="flex items-center gap-2.5 px-5 py-4 border-b border-brand/10">
              <div className="w-7 h-7 rounded-lg bg-brand flex items-center justify-center shrink-0">
                <svg viewBox="0 0 24 24" className="w-3.5 h-3.5 text-white fill-none stroke-current stroke-2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                </svg>
              </div>
              <div>
                <p className="text-sm font-bold text-fg leading-tight">
                  Background removed by Photoroom API
                </p>
                <p className="text-xs text-fg-muted">
                  Any product photo → studio-ready image in seconds
                </p>
              </div>
            </div>

            {/* Before / After split */}
            <div className="grid grid-cols-2 gap-0">

              {/* Before */}
              <div className="flex flex-col gap-2 p-4 border-r border-brand/10">
                <div className="flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-fg-muted/40 shrink-0" aria-hidden="true" />
                  <span className="text-xs font-semibold text-fg-muted uppercase tracking-wider">Original photo</span>
                </div>
                <div className="rounded-xl overflow-hidden border border-border-subtle aspect-square">
                  <Image
                    src="/examples/instagram.webp"
                    alt="Original product photo — sneaker on outdoor background before Photoroom"
                    width={1024}
                    height={1024}
                    className="w-full h-full object-cover"
                    sizes="(max-width: 640px) 45vw, 25vw"
                  />
                </div>
                <p className="text-[11px] text-fg-muted text-center">Any background, any lighting</p>
              </div>

              {/* After */}
              <div className="flex flex-col gap-2 p-4 relative">
                {/* Purple arrow on the divider */}
                <div className="absolute left-0 top-1/2 -translate-x-1/2 -translate-y-1/2 z-10 w-7 h-7 rounded-full bg-brand shadow-md flex items-center justify-center">
                  <svg viewBox="0 0 24 24" className="w-3.5 h-3.5 text-white fill-none stroke-current stroke-2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    <path d="M5 12h14M12 5l7 7-7 7"/>
                  </svg>
                </div>

                <div className="flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-brand shrink-0" aria-hidden="true" />
                  <span className="text-xs font-bold text-brand uppercase tracking-wider">Processed by Photoroom ✨</span>
                </div>
                <div className="rounded-xl overflow-hidden border border-brand/20 aspect-square shadow-sm bg-white">
                  <Image
                    src="/examples/amazon.webp"
                    alt="Product after Photoroom processing — clean white background, studio quality"
                    width={1024}
                    height={1024}
                    className="w-full h-full object-cover"
                    sizes="(max-width: 640px) 45vw, 25vw"
                  />
                </div>
                <p className="text-[11px] text-brand font-medium text-center">Background removed · Studio quality</p>
              </div>
            </div>

            {/* Feature tags */}
            <div className="flex flex-wrap gap-2 px-5 py-3 border-t border-brand/10 bg-white/50">
              {[
                'Background removal',
                'AI lighting per channel',
                'Custom style per platform',
                '5 formats in one API call',
              ].map((tag) => (
                <span key={tag} className="text-xs font-medium text-brand bg-brand-soft border border-brand/20 px-2.5 py-1 rounded-full">
                  ✓ {tag}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* ── Images sub-section ──────────────────────────────────────────────── */}
        <div className="mb-16">
          <div className="flex items-center gap-3 mb-6">
            <h3 className="text-base font-semibold text-fg">
              5 images optimized by channel
            </h3>
            <span className="text-xs font-medium text-fg-muted bg-background border border-border-subtle rounded-full px-2.5 py-1">
              Generated in ~25s
            </span>
          </div>

          {/*
            Grid: 3 columns × 2 rows, items-start.
            Row 1: Amazon · Instagram · Ads           (all aspect-square)
            Row 2: Pinterest · TikTok (9:16) · Staging (square)

            Layout rationale: TikTok (9:16) in center of row 2 is intentional —
            Pinterest and Staging flank it as square cards, items-start aligned.
            The height contrast visually communicates "different format for different
            platform", which is the whole value prop of the tool.

            SM (2-col): 3 rows of 2 → Amazon/Instagram, Ads/Pinterest, TikTok/Staging
            Mobile: 1 col, all stacked
          */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 items-start">
            {MOCKUP_IMAGES.map((img) => (
              <MockupCard
                key={img.style}
                label={img.label}
                src={img.src}
                width={img.width}
                height={img.height}
                alt={img.alt}
                aspectClass={img.aspect}
              />
            ))}
            <StagingCard />
          </div>
        </div>

        {/* ── Copy sub-section ────────────────────────────────────────────────── */}
        <div className="mb-14">
          <div className="rounded-2xl border border-border-subtle bg-background overflow-hidden shadow-sm">

            <div className="flex items-center justify-between px-6 py-4 border-b border-border-subtle bg-background-soft">
              <div className="flex items-center gap-3 flex-wrap">
                <span className="text-xs font-semibold text-white bg-brand px-2.5 py-1 rounded-full">
                  Detected: Shopify merchant
                </span>
                <span className="text-xs text-fg-muted">
                  Generated in ~8s · Adapted to DTC brand-first tone
                </span>
              </div>
              <button
                type="button"
                onClick={handleCopyAll}
                aria-label="Copy all copy to clipboard"
                className="flex items-center gap-1.5 text-xs font-medium text-fg-muted border border-border-subtle rounded-lg px-3 py-1.5 hover:border-brand/50 hover:text-brand hover:bg-brand-soft transition-colors outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-1 shrink-0"
              >
                <Copy size={13} aria-hidden="true" />
                Copy all
              </button>
            </div>

            <div className="p-6 flex flex-col gap-8">

              <div>
                <h3 className="text-xs font-semibold text-brand uppercase tracking-widest mb-3">
                  SEO Description
                  <span className="ml-2 text-fg-muted normal-case font-normal tracking-normal">157 words</span>
                </h3>
                <p className="text-sm text-fg leading-relaxed">
                  {SAMPLE_COPY.description}
                </p>
              </div>

              <div>
                <h3 className="text-xs font-semibold text-brand uppercase tracking-widest mb-3">
                  5 Bullets
                </h3>

                <ul className="flex flex-col gap-2.5">
                  {SAMPLE_COPY.bullets.map((bullet, i) => (
                    <li key={i} className="flex items-start gap-2.5 text-sm text-fg">
                      <span className="mt-0.5 shrink-0 w-5 h-5 rounded-full bg-brand-soft text-brand flex items-center justify-center text-[10px] font-bold">
                        {i + 1}
                      </span>
                      {bullet}
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <h3 className="text-xs font-semibold text-brand uppercase tracking-widest mb-3">
                  Tweet
                  <span className="ml-2 text-fg-muted normal-case font-normal tracking-normal">279 characters</span>
                </h3>
                <blockquote className="text-sm text-fg leading-relaxed bg-background-soft rounded-xl p-4 border border-border-subtle italic">
                  &ldquo;{SAMPLE_COPY.tweet}&rdquo;
                </blockquote>
              </div>

            </div>
          </div>
        </div>

        {/* ── Sub-CTA ─────────────────────────────────────────────────────────── */}
        <div className="flex flex-col items-center gap-4 text-center">
          <p className="text-lg font-semibold text-fg">
            Impressed? Do it with your product in 30 seconds.
          </p>
          <button
            type="button"
            onClick={handleScrollToInput}
            className="h-12 px-8 rounded-lg font-semibold text-base text-white bg-brand hover:bg-brand-hover active:scale-[0.98] transition-all duration-150 outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-2"
          >
            Try with my URL →
          </button>
        </div>

      </div>
    </section>
  )
}
