// ─── Product data extracted by Firecrawl from the seller's URL ───────────────

export interface ScrapedProduct {
  title: string
  description: string
  price?: string
  imageUrl: string
  sourceUrl: string
}

// ─── Copy generated by Claude ─────────────────────────────────────────────────

export type Platform = 'shopify' | 'etsy' | 'amazon' | 'generic'

export interface GeneratedCopy {
  description: string  // ~150 words, SEO-optimized
  bullets: [string, string, string, string, string]  // exactly 5
  tweet: string        // ≤280 chars
  detectedPlatform: Platform  // used in UI for badge + CTA personalization
}

// ─── Photoroom image processing ───────────────────────────────────────────────

export type ImageStyle = 'amazon' | 'instagram' | 'ads' | 'pinterest' | 'tiktok'

export interface ProcessedImage {
  style: ImageStyle
  channelLabel: string  // display label shown in the UI
  imageUrl: string      // URL of the processed image returned by Photoroom
  originalUrl: string   // original product image URL (before processing)
}

// ─── Lead capture ─────────────────────────────────────────────────────────────

export interface Lead {
  email: string
  productUrl: string
  createdAt: string  // ISO 8601, e.g. "2026-04-17T10:30:00.000Z"
}

// ─── Full kit result ───────────────────────────────────────────────────────────

export interface GeneratedKit {
  scraped: ScrapedProduct
  copy: GeneratedCopy
  images: ProcessedImage[]
}

// ─── App state machine ────────────────────────────────────────────────────────

export type AppState =
  | 'idle'          // user hasn't done anything yet
  | 'scraping'      // Firecrawl is fetching the product page
  | 'generating'    // Claude is writing the copy
  | 'processing'    // Photoroom is generating the 5 images
  | 'email_gate'    // kit is ready, waiting for email before revealing
  | 'results'       // kit fully visible
  | 'error'         // something failed

// ─── API response shapes (internal — used in API routes, not exported to UI) ──

interface ApiSuccessResponse<T> {
  success: true
  data: T
}

interface ApiErrorResponse {
  success: false
  error: string
}

export type ApiResponse<T> = ApiSuccessResponse<T> | ApiErrorResponse

// ─── Photoroom style config (internal — consumed by lib/photoroom.ts) ─────────

interface PhotoroomStyleConfig {
  style: ImageStyle
  channelLabel: string
  params: Record<string, unknown>  // Photoroom API params vary per style
}

export type PhotoroomStyleMap = PhotoroomStyleConfig[]
